trigger:
  branches:
    include:
    - main
  paths:
    include:
    - sdk/iot/

variables:
  Skip_Analyze: true
  Skip_Test: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: iot
    ArtifactName: packages
    Artifacts:
    - name: Azure.IoT.Hub.Service
      safeName: AzureIoTHubService
